---
Name: 'lingo'
After: 'i18nMessages'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - NorthCreationAgency\SilverStripeLingo\LingoPageExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\i18n\Messages\MessageProvider:
    class: NorthCreationAgency\SilverStripeLingo\LingoMessageProvider
#NorthCreationAgency\SilverStripeLingo\Lingo:
#  moduleCatalog: lingo
#  textCatalog: text