---
Name: 'lingo'
After:
  - 'i18nMessages'
  - '#corecache'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - NorthCreationAgency\SilverStripeLingo\LingoPageExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\i18n\Messages\MessageProvider:
    class: NorthCreationAgency\SilverStripeLingo\LingoMessageProvider
  Psr\SimpleCache\CacheInterface.LingoCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "LingoCache"
   
#NorthCreationAgency\SilverStripeLingo\Lingo:
#  moduleCatalog: lingo
#  textCatalog: text