---
Name: 'lingo'
After:
  - 'i18nMessages'
  - '#corecache'
---
SilverStripe\ORM\DataObject:
  extensions:
    - NorthCreationAgency\SilverStripeLingo\LingoDOExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\i18n\Messages\MessageProvider:
    class: NorthCreationAgency\SilverStripeLingo\LingoMessageProvider
  Psr\SimpleCache\CacheInterface.LingoCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "LingoCache"

SilverStripe\ORM\ArrayList:
  extensions:
    - NorthCreationAgency\SilverStripeLingo\ArrayListRandomSortExtension      
   
#NorthCreationAgency\SilverStripeLingo\Lingo:
#  moduleCatalog: lingo
#  textCatalog: text